name: PR-Agent Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pr-agent-review:
    runs-on: ubuntu-latest

    steps:
      - uses: codium-ai/pr-agent@main
        with:
          pr_agent_token: ${{ secrets.OPENAI_KEY }}
          pr_agent_model: "openrouter/anthropic/claude-3.7-sonnet"
          pr_agent_system_prompt: "You are a helpful AI assistant that reviews code changes with a focus on font implementations, CSS/SASS best practices, and general code quality. Pay special attention to @font-face declarations, font loading performance, and proper use of !important."
          pr_agent_verbose: "true"
          pr_agent_review_comment_enabled: "true"
          pr_agent_inline_comment_enabled: "true"

